# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Intel® Smart Edge Open
description:        Documentation
lang:               en

# Site subpath, e.g. /blog
baseurl:            "/ido-specs"

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                ""

main_url:           "https://intelsmartedge.github.io"

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:               

navbar:
    sticky:         true
    search:         true
  
# Default author settings
author:
    name:           Pete Seth
    title:          Lead Developer  
    avatar:         avatar-tom.png

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    john:
      name:         John Brown
      title:        Support     
      avatar:       avatar-john.png
    evan:
      name:         Evan Wells
      title:        Support    
      avatar:       avatar-evan.png
    sara:
      name:         Sara Galen
      title:        Lead Developer     
      avatar:       avatar-sara.png
    alex:
      name:         Alex Koch
      title:        Design Engineer     
      avatar:       avatar-alex.png
    daniel:
      name:         Daniel Shultz
      title:        Developer      
      avatar:       avatar-daniel.png
    tom:
      name:         Tom Farrell
      title:        Developer     
      avatar:       avatar-tom.png

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics: true

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output:         true
  faqs:
    output:         false
  changelogs:
    output:         false
